"""Alembic env — uses our SQLAlchemy models + engine."""

from logging.config import fileConfig

from alembic import context

from gitd.models.base import Base, engine

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Import all models so autogenerate can detect them
from gitd.models import *  # noqa: E402, F401, F403

target_metadata = Base.metadata


def _process_revision_directives(context, revision, directives):
    """Filter out SQLite false-positive diffs from autogenerated migrations.

    SQLite's inspector reports INTEGER PRIMARY KEY as nullable=True,
    causing permanent phantom modify_nullable ops. Strip them.
    Also drop the migration file entirely if nothing real remains.
    """
    if not directives:
        return
    script = directives[0]
    if not script.upgrade_ops:
        return

    from alembic.operations.ops import ModifyTableOps

    cleaned = []
    for op in script.upgrade_ops.ops:
        if isinstance(op, ModifyTableOps):
            # Filter out nullable-only changes on PK columns
            op.ops = [
                inner
                for inner in op.ops
                if not (
                    hasattr(inner, "modify_nullable")
                    and inner.modify_nullable is False
                    and inner.existing_nullable is True
                )
            ]
            if op.ops:  # keep table op only if non-empty
                cleaned.append(op)
        else:
            cleaned.append(op)

    script.upgrade_ops.ops = cleaned
    if not cleaned:
        directives[:] = []  # empty migration — don't generate file


def run_migrations_offline() -> None:
    url = str(engine.url)
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=False,
        compare_server_default=False,
        process_revision_directives=_process_revision_directives,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=False,
            compare_server_default=False,
            process_revision_directives=_process_revision_directives,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
