#!/usr/bin/env python3
"""Burn timestamped test logs as a terminal-style overlay onto a screen recording.

Usage:
    python3 gen_video_overlay.py <video.mp4> <logfile> [output.mp4]

If output is omitted, writes to <video>_overlay.mp4.

Requires: ffmpeg, timestamped log lines in [HH:MM:SS] format (generated by server.py test runner).
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

# ── Overlay style config ─────────────────────────────────────────────────────
MAX_VISIBLE = 18  # max lines on screen at once
FONT_SIZE = 34
LINE_HEIGHT = 42
MAX_CHARS = 48  # chars per line before wrapping
MARGIN_LEFT = 12
MARGIN_TOP_PCT = 0.65  # start text at 65% from top (35% above bottom)
STAGGER_MS = 200  # ms gap between lines sharing the same second


def _color_for_line(line):
    if "PASSED" in line:
        return "4ADE80"
    if "FAILED" in line or "ERROR" in line or line.startswith("E "):
        return "FF4444"
    if line.startswith("===") or line.startswith("---") or line.startswith("___"):
        return "6366F1"
    if line.startswith("["):
        return "22FF88"
    return "22FF22"


def _ts_to_seconds(ts_str):
    h, m, s = ts_str.split(":")
    return int(h) * 3600 + int(m) * 60 + int(s)


def _fmt_ass_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    cs = int((s - int(s)) * 100)
    return f"{h}:{m:02d}:{int(s):02d}.{cs:02d}"


def _get_video_height(video_path):
    """Get video height via ffprobe."""
    try:
        out = (
            subprocess.check_output(
                [
                    "ffprobe",
                    "-v",
                    "quiet",
                    "-select_streams",
                    "v:0",
                    "-show_entries",
                    "stream=height",
                    "-of",
                    "csv=p=0",
                    str(video_path),
                ],
                timeout=10,
            )
            .decode()
            .strip()
        )
        return int(out)
    except Exception:
        return 2340  # default for phone recordings


def generate_overlay(video_path, log_path, output_path=None):
    """Generate an overlay video with terminal-style log text burned in.

    Args:
        video_path: Path to source MP4 (screen recording)
        log_path: Path to timestamped log file ([HH:MM:SS] prefixed lines)
        output_path: Output MP4 path. Defaults to <video>_overlay.mp4

    Returns:
        Path to output file, or None on failure.
    """
    video_path = Path(video_path)
    log_path = Path(log_path)
    if output_path is None:
        output_path = video_path.with_name(video_path.stem + "_overlay.mp4")
    else:
        output_path = Path(output_path)

    # Parse timestamped log lines
    entries = []
    first_ts = None
    for line in log_path.read_text(errors="replace").splitlines():
        m = re.match(r"^\[(\d{2}:\d{2}:\d{2})\] (.*)$", line)
        if not m:
            continue
        ts_s = _ts_to_seconds(m.group(1))
        text = m.group(2)
        if not text.strip():
            continue
        if first_ts is None:
            first_ts = ts_s
        entries.append((ts_s - first_ts, text))

    if not entries:
        print("No timestamped lines found in log", file=sys.stderr)
        return None

    # Wrap long lines
    wrapped = []
    for t, text in entries:
        while len(text) > MAX_CHARS:
            wrapped.append((t, text[:MAX_CHARS]))
            text = "  " + text[MAX_CHARS:]
        wrapped.append((t, text))
    entries = wrapped

    # Stagger lines sharing the same second
    staggered = []
    prev_t = -1
    same_count = 0
    for t, text in entries:
        if t == prev_t:
            same_count += 1
        else:
            same_count = 0
            prev_t = t
        staggered.append((t + same_count * STAGGER_MS / 1000.0, text))
    entries = staggered

    N = len(entries)
    video_end = entries[-1][0] + 5
    video_height = _get_video_height(video_path)
    margin_top = int(video_height * MARGIN_TOP_PCT)

    # Generate ASS subtitle file
    ass_lines = [
        f"""[Script Info]
Title: Test Log Overlay
ScriptType: v4.00+
PlayResX: 1080
PlayResY: {video_height}
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Log,Courier New,{FONT_SIZE},&H0022FF22,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,3,0,4,7,20,20,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"""
    ]

    for i in range(N):
        text = entries[i][1]
        safe = text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
        col = _color_for_line(entries[i][1])
        r, g, b = col[0:2], col[2:4], col[4:6]
        ass_col = f"&H{b}{g}{r}&"

        for row in range(MAX_VISIBLE):
            j = i + row
            if j >= N:
                t_start = entries[min(j, N - 1)][0] if j > i else entries[i][0]
                if j > i and j >= N:
                    break
                t_end = video_end
            else:
                t_start = entries[j][0]
                t_end = entries[j + 1][0] if (j + 1) < N else video_end

            if t_start >= video_end:
                break
            if t_end - t_start < 0.01:
                continue
            if t_end > video_end:
                t_end = video_end

            y = margin_top + row * LINE_HEIGHT
            pos = f"\\pos({MARGIN_LEFT},{y})"
            style = f"\\c{ass_col}\\3c&H000000&\\alpha&H20&"
            ass_lines.append(
                f"Dialogue: 0,{_fmt_ass_time(t_start)},{_fmt_ass_time(t_end)},Log,,0,0,0,,{{{pos}{style}}}{safe}"
            )

    # Write ASS to temp file and run ffmpeg
    with tempfile.NamedTemporaryFile(mode="w", suffix=".ass", delete=False) as f:
        f.write("\n".join(ass_lines))
        ass_path = f.name

    try:
        result = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(video_path),
                "-vf",
                f"ass={ass_path}",
                "-c:v",
                "libx264",
                "-preset",
                "fast",
                "-crf",
                "28",
                "-an",
                str(output_path),
            ],
            capture_output=True,
            timeout=600,
        )
        if result.returncode != 0:
            print(f"ffmpeg failed: {result.stderr.decode()[-500:]}", file=sys.stderr)
            return None
        return output_path
    except Exception as e:
        print(f"Overlay generation failed: {e}", file=sys.stderr)
        return None
    finally:
        Path(ass_path).unlink(missing_ok=True)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    video = sys.argv[1]
    log = sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else None
    result = generate_overlay(video, log, out)
    if result:
        print(f"Overlay video: {result}")
    else:
        sys.exit(1)
